---
title: 'Estratégias para a Mega-sena'
subtitle: 'scratch'
author: 'fnaufel'
email: 'https://fnaufel.github.io/'
date: 'Versão de `r format(Sys.Date(), "%d/%m/%Y")`'
lang: 'pt'
# TODO: include LaTeX fields
output: 
  html_document:
    theme: readable
           # https://bootswatch.com/3/readable/
    highlight: tango
    css: styles.css
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
    df_print: paged
    self_contained: true
    # code_folding: show
    # keep_md: true
    # includes:
    #   in_header: header.html
    #   before_body: doc_prefix.html
    #   after_body: doc_suffix.html
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(
  echo = TRUE,
  # collapse = TRUE,
  # cache = TRUE,
  out.width = "75%",
  fig.align = 'center',
  # fig.width = 6,
  fig.show = "hold"
)

options(dplyr.print_min = 6, dplyr.print_max = 6)

# Supress crayon output
options(crayon.enabled = FALSE)

# For nice dataframe summaries
library(summarytools)
st_options(
  plain.ascii = FALSE,
  dfSummary.varnumbers = FALSE,
  dfSummary.style = 'grid',
  dfSummary.graph.magnif = .75
)

# Tidy!
library(tidyverse)

# Sober theme for ggplot
theme_set(
  theme_linedraw() +                         # Set simple theme for ggplot
    theme(                                   # with some tweaks
      axis.title.y.left = element_text(
         angle = 0,                          # Never rotate y axis title
         margin = margin(r = 20),            # Separate y axis title a little 
         vjust = .5                          # Leave y axis title in the middle
      ),
      axis.title.x.bottom = element_text(
         margin = margin(t = 20)             # Separate x axis title a little 
      ),
      axis.line = element_blank(),           # No axis lines
      panel.border = element_blank(),        # No frame
      panel.grid.minor = element_blank()     # No grid minor lines
    )
)

# Avoid scientific notation and use a comma as decimal separator
options(
  scipen = 15,
  OutDec = ','
)

# Format a number with thousand separators (default point)
# and decimal comma enclosed in curly braces for LaTeX printing.
# CAREFUL: if called outside math mode, will print the braces!
fm <- function(x, big = '.', decimal = '{,}') {
  if (!is.numeric(x)) {
    x
  } else {
    prettyNum(x, big.mark = big, decimal.mark = decimal)
  }

}

# To center the results of a chunk (image, video etc.)
# Usage: 
#         out.extra=center()
#         
center <- function(){
  
  if (is_html_output()) {
    'class="center"'
  }
  
}


# To embed YT videos in HTML and the link (centered) in LaTeX
embed_yt <- function(code) {

  if (is_html_output()) {
    include_url(
      paste0(
        'https://www.youtube.com/embed/',
        code
      )
    )
  } else {
    cat(
      paste0(
        '```{=latex}\n',
        '\\begin{center} \\url{https://youtu.be/',
        code,
        '} \\end{center}\n',
        '```'
      )
    )
  }
  
}

source('../packages.R')

```

```{js javascript-init, echo=FALSE}

// Make off-site links open in a new window/tab
function changeTargets() {
  $("a").attr(
    "target", function() {
      // Load local links locally
      if (this.host == location.host) return "_self"
      // Load off-site links in a new window
      else return "_blank";
    }
  );
}

// Execute when document is ready
$(
  changeTargets
)
```

# Dados

```{r}
loadd(df_vetor)

n_recentes = 300

df_regress <- df_vetor %>% 
  # Criar lag da estimativa de arrecadação e mudar unidades
  mutate(
    est_arrec = lag(est_prox) / 1e6,       # arrecadação em milhões
    across(starts_with('r_'), ~ .x/1e3),   # rateios em milhares
    .keep = 'unused'
  ) %>% 
  # A partir de `num` = 869, `est_prox` está preenchida
  # A partir de `num` = 1077, `arrec` está preenchida
  # Usar concursos a partir do ano de 2010 (concurso 1141).
  filter(num >= 1141) %>% 
  # Retirar os concursos da virada, que têm valores atípicos
  filter(
    !(month(data) == 12 & day(data) == 31)
  ) %>%
  # Tomar apenas os `n_recentes` concursos
  slice_tail(n = n_recentes) %>% 
  # Escolher colunas
  select(num, data, est_arrec, starts_with(c('r_', 'g_')))

```




# r_quina ~ est_arrec: horrível

## Scatterplot

```{r}
df_regress %>% 
  ggplot() +
    geom_point(aes(est_arrec, r_quina)) +
    labs(
      x = 'arrec (milhões)',
      y = 'rateio\n(milhares)'
    )
```

## Transformando: também horrível

```{r}
df_regress %>% 
  ggplot(aes(log(est_arrec), r_quina)) +
    geom_point() +
    geom_smooth(method = 'lm', se = FALSE) +
    labs(
      x = 'log (arrec (milhões))',
      y = 'rateio\n(milhares)'
    )
```


# r_quina ~ est_arrec? Horrível

```{r}
df_regress %>% 
  ggplot(aes(est_arrec, r_quina)) +
    geom_point() +
    geom_smooth(method = 'lm', se = FALSE) +
    labs(
      x = 'est. arrec. (milhões)',
      y = 'rateio\n(milhares)'
    )
```

# Tentar r_quina ~ g_quina? LOESS

## Scatterplot

```{r}
df_regress %>% 
  ggplot() +
    geom_point(aes(g_quina, r_quina)) +
    labs(
      x = 'ganhadores',
      y = 'rateio\n(milhares)'
    )
```

## Usar LOESS?

```{r}
df_regress %>% 
  ggplot(aes(sqrt(g_quina), r_quina)) +
    geom_point() +
    geom_smooth(se = FALSE) +
    labs(
      x = 'sqrt ganhadores',
      y = 'rateio\n(milhares)'
    )
```

